spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。
      #在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
      poolPreparedStatements: true
      #配置扩展插件:监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
      filters: stat
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

      # mysql数据库基本配置
#      master:
#        url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#        username: root
#        password: 123
#        driver-class-name: com.mysql.cj.jdbc.Driver
  #      core:
#        jdbcUrl: jdbc:oracle:thin:@10.156.14.126:1521:lisst
#        usename: lis
#        password: Lis$1243
#        driver-class-name: oracle.jdbc.driver.OracleDriver   #可配可不配，阿里的数据库连接池会通过url自动搜寻
  redis:
    # redis策略，1,单机模式 2，集群模式，3，哨兵模式
    strategy: 1
    host: localhost
    port: 6379
    #    sentinel:
    #      master: mymaster
    #      nodes: 127.0.0.1:26379,127.0.0.1:27001,127.0.0.1:27002
    timeout: 3000
    jedis:
      pool:
        maxActive: 8  # 连接池最大连接数 (使用负值表示没有限制)
        maxWait: -1   # 连接池最大阻塞等待时间 (使用负值表示没有限制)
        maxIdle: 8    # 连接池中的最大空闲连接
        minIdle: 0     # 连接池中的最小空闲连接
    database: 1
mail-config:
  environmental: dev测试
  from: Lchengli@qq.com
  recipient:
    - "595105385@qq.com"
    - "lichengli@sinosoft.com.cn"
logging:
  level:
    com.micro.lcl: debug
    org.springframework.web: debug
    org.springframework.boot: debug