server:
  port: 9000
spring:
  application:
    name: lcl-sleb
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    username: Lchengli@qq.com
    password: euhtnwyihvvwbccg
    default-encoding: utf-8
    port: 587
    protocol: smtp
    properties:
      mail:
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: false
            required: false
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1   #设置一次处理一个消息
        acknowledge-mode: manual  #设置消费端手动 ack
        concurrency: 3     #设置同时有3个消费者消费
        retry:
          #最大重试传递次数
          max-attempts: 3
          initial-interval: 5000ms #第一次和第二次尝试传递消息的间隔时间 单位毫秒
          max-interval: 300000ms #最大重试时间间隔，单位毫秒
          multiplier: 3 #应用前一次重试间隔的乘法器，multiplier默认为1  #以上配置的间隔0s  5s  15s  45s
        default-requeue-rejected: true   #重试次数超过上面的设置之后是否丢弃(消费者listener抛出异常，是否重回队列，默认true：重回队列， false为不重回队列(结合死信交换机))
    connection-timeout: 500
    # 确认消息是否正确到达queue,如果没有则触发，如果有则不触发
    publisher-returns: true #发布者到达确认
    publisher-confirm-type: correlated #发布者确认
    template:
      ### 模板配置
      ##设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除
      mandatory: true